#ifndef ENUM_ATTRIBUTELAYOUT_HEADER
#define ENUM_ATTRIBUTELAYOUT_HEADER

enum AttributeLayout
{
        ATTRIBUTE_POSITION = 0,
        ATTRIBUTE_NORMAL = 1,
        ATTRIBUTE_UV = 2
};

#endif // ENUM_ATTRIBUTELAYOUT_HEADER
